fix agenda.js
kodaitakahashi/appdoc pull request #2
Opened 2018-03-05 15:08 UTC by kodaitakahashi

2018-03-05 15:33 UTC, yuk4w4 requested changes
レビューしました。ちょい直してほしいとこがありまっす 🍖

2018-03-05 15:33 UTC, offxi commented on agenda.json
> +                  "example": "管理ID"
例がこれで良い? 本来は半角英数的なものとかシーケンシャルな数値が入るのでは?

2018-03-05 15:33 UTC, offxi commented on agenda.json
> +                  "example": [
本来exampleはマジでありえる値のほうが嬉しいと思うなー

2018-03-05 15:33 UTC, offxi commented on agenda.json
> +                "agenda_id": {
更新時もIDはパスでは? 🐪

2018-03-06 12:41 UTC, closed without merging

2018-03-06 12:46 UTC, kodaitakahashi commented on agenda.json
> +                  "example": "管理ID"
カテゴリID-ハッシュ値で返す考えなので、exampleにそのような値を入れます。

2018-03-06 12:46 UTC, kodaitakahashi commented on agenda.json
> +                  "example": [
exampleに実際に入る内容を入れていきます。

2018-03-06 12:47 UTC, kodaitakahashi commented on agenda.json
> +                "agenda_id": {
更新時のidもpathなのでpathに修正します。